// Fetches the OpenAPI schema of the Quak API and writes the committed snapshot (openapi.json) and the generated
// types (src/generated/schema.ts). Builds only read the snapshot, they never need a running API. `bun generate` then
// runs scripts/docs.ts, which updates the parameter tables in README.md.
//
//   bun generate                                  # production API (the snapshot for releases)
//   bun generate http://localhost:3101/openapi/json   # local dev API, to try unreleased routes
//   QUAK_OPENAPI_URL=http://localhost:3101/openapi/json bun generate
//   bun generate ./openapi.json                   # regenerate the types from the snapshot only

import openapiTS, { astToString } from "openapi-typescript";

const DEFAULT_URL = "https://api.quak.party/openapi/json";
const source = process.argv[2] ?? process.env.QUAK_OPENAPI_URL ?? DEFAULT_URL;
const root = new URL("..", import.meta.url);

async function load(source: string): Promise<Record<string, unknown>> {
  if (!/^https?:\/\//.test(source)) {
    return Bun.file(source).json();
  }
  const response = await fetch(source, { headers: { accept: "application/json" } });
  if (!response.ok) {
    throw new Error(`GET ${source}: ${response.status} ${response.statusText}`);
  }
  return response.json() as Promise<Record<string, unknown>>;
}

const schema = await load(source);
if (typeof schema.openapi !== "string" || typeof schema.paths !== "object") {
  throw new Error(`${source} is not an OpenAPI document`);
}

const header = [
  "// Generated by scripts/generate.ts from openapi.json with openapi-typescript. Do not edit, run `bun generate`.",
  "",
].join("\n");
const types = header + astToString(await openapiTS(schema as never));

await Bun.write(new URL("openapi.json", root), JSON.stringify(schema, null, 2) + "\n");
await Bun.write(new URL("src/generated/schema.ts", root), types);

const paths = Object.keys(schema.paths as object).length;
console.log(`${source} → openapi.json, src/generated/schema.ts (${paths} paths)`);
